<?php

use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('categories')->insert(['nombre' => 'Almacen', 'padre' => '0']);
        DB::table('categories')->insert(['nombre' => 'Golosinas', 'padre' => '1']);
        DB::table('categories')->insert(['nombre' => 'Alfajores', 'padre' => '2']);
        DB::table('categories')->insert(['nombre' => 'Bombones y bocadillos', 'padre' => '2']);
        DB::table('categories')->insert(['nombre' => 'caramelos y chupetines', 'padre' => '2']);
        DB::table('categories')->insert(['nombre' => 'chicles y pastillas', 'padre' => '2']);
        DB::table('categories')->insert(['nombre' => 'Endulzantes', 'padre' => '1']);
        DB::table('categories')->insert(['nombre' => 'Azucar', 'padre' => '7']);
        DB::table('categories')->insert(['nombre' => 'Edulcorante', 'padre' => '7']);
        DB::table('categories')->insert(['nombre' => 'Encurtidos', 'padre' => '1']);
        DB::table('categories')->insert(['nombre' => 'Aceitunas', 'padre' => '10']);
        DB::table('categories')->insert(['nombre' => 'Aji', 'padre' => '10']);
        DB::table('categories')->insert(['nombre' => 'Alcaparras', 'padre' => '10']);
        DB::table('categories')->insert(['nombre' => 'Berenjenas', 'padre' => '10']);
        DB::table('categories')->insert(['nombre' => 'Alimento de bebes y niños', 'padre' => '1']);
        DB::table('categories')->insert(['nombre' => 'Alimentos para bebes', 'padre' => '15']);
        DB::table('categories')->insert(['nombre' => 'infusiones infantiles', 'padre' => '15']);
        DB::table('categories')->insert(['nombre' => 'Harinas', 'padre' => '1']);
        DB::table('categories')->insert(['nombre' => 'Harina de trigo', 'padre' => '18']);
        DB::table('categories')->insert(['nombre' => 'Harina de maiz', 'padre' => '18']);
        DB::table('categories')->insert(['nombre' => 'Premezcla', 'padre' => '18']);
        DB::table('categories')->insert(['nombre' => 'Semola', 'padre' => '18']);
        DB::table('categories')->insert(['nombre' => 'Aderezos', 'padre' => '1']);
        DB::table('categories')->insert(['nombre' => 'Mayonesas', 'padre' => '23']);
        DB::table('categories')->insert(['nombre' => 'Mostazas', 'padre' => '23']);
        DB::table('categories')->insert(['nombre' => 'Ketchup', 'padre' => '23']);
        DB::table('categories')->insert(['nombre' => 'Salsas golf', 'padre' => '23']);
        DB::table('categories')->insert(['nombre' => 'Infusiones', 'padre' => '1']);
        DB::table('categories')->insert(['nombre' => 'Mate', 'padre' => '28']);
        DB::table('categories')->insert(['nombre' => 'Te', 'padre' => '28']);
        DB::table('categories')->insert(['nombre' => 'Cafe', 'padre' => '28']);
        DB::table('categories')->insert(['nombre' => 'Mate cocido', 'padre' => '28']);
        DB::table('categories')->insert(['nombre' => 'Conservas', 'padre' => '1']);
        DB::table('categories')->insert(['nombre' => 'Conservas vegetal', 'padre' => '33']);
        DB::table('categories')->insert(['nombre' => 'Conservas de pescado', 'padre' => '33']);
        DB::table('categories')->insert(['nombre' => 'Conservas de fruta', 'padre' => '33']);
        DB::table('categories')->insert(['nombre' => 'Conservas de carne', 'padre' => '33']);
        DB::table('categories')->insert(['nombre' => 'Mermeladas y dulces', 'padre' => '1']);
        DB::table('categories')->insert(['nombre' => 'Mermeladas', 'padre' => '38']);
        DB::table('categories')->insert(['nombre' => 'Miel', 'padre' => '38']);
        DB::table('categories')->insert(['nombre' => 'Jalea', 'padre' => '38']);
        DB::table('categories')->insert(['nombre' => 'Dulce', 'padre' => '38']);
        DB::table('categories')->insert(['nombre' => 'Salsas y pure de tomate', 'padre' => '1']);
        DB::table('categories')->insert(['nombre' => 'Extracto tomates', 'padre' => '43']);
        DB::table('categories')->insert(['nombre' => 'Pulpa de tomate', 'padre' => '43']);
        DB::table('categories')->insert(['nombre' => 'Pure de tomate', 'padre' => '43']);
        DB::table('categories')->insert(['nombre' => 'Salsa de tomates dkt', 'padre' => '43']);
        DB::table('categories')->insert(['nombre' => 'Aceites y condimentos', 'padre' => '1']);
        DB::table('categories')->insert(['nombre' => 'Aceites', 'padre' => '48']);
        DB::table('categories')->insert(['nombre' => 'Condimentos', 'padre' => '48']);
        DB::table('categories')->insert(['nombre' => 'Vinagres', 'padre' => '48']);
        DB::table('categories')->insert(['nombre' => 'Sopas, caldos, pure y saborizantes', 'padre' => '1']);
        DB::table('categories')->insert(['nombre' => 'Mezcla lista', 'padre' => '52']);
        DB::table('categories')->insert(['nombre' => 'Sopas y saborizantes', 'padre' => '52']);
        DB::table('categories')->insert(['nombre' => 'Arroz y legumbres', 'padre' => '1']);
        DB::table('categories')->insert(['nombre' => 'Arroz', 'padre' => '55']);
        DB::table('categories')->insert(['nombre' => 'Legumbres', 'padre' => '55']);
        DB::table('categories')->insert(['nombre' => 'Panaderia', 'padre' => '1']);
        DB::table('categories')->insert(['nombre' => 'Bizcochos', 'padre' => '58']);
        DB::table('categories')->insert(['nombre' => 'Bizcochuelos y especialidades', 'padre' => '58']);
        DB::table('categories')->insert(['nombre' => 'Galletas, tostadas y grisines', 'padre' => '58']);
        DB::table('categories')->insert(['nombre' => 'Panificados', 'padre' => '58']);
        DB::table('categories')->insert(['nombre' => 'Especias', 'padre' => '1']);
        DB::table('categories')->insert(['nombre' => 'Especias', 'padre' => '63']);
        DB::table('categories')->insert(['nombre' => 'Semillas', 'padre' => '63']);
        DB::table('categories')->insert(['nombre' => 'Pasta seca, lista y rellenas', 'padre' => '1']);
        DB::table('categories')->insert(['nombre' => 'Pasta lista y rellenas', 'padre' => '66']);
        DB::table('categories')->insert(['nombre' => 'Pastas secas', 'padre' => '66']);
        DB::table('categories')->insert(['nombre' => 'Polvo para postres y reposteria', 'padre' => '66']);
        DB::table('categories')->insert(['nombre' => 'Premezcla postres', 'padre' => '66']);
        DB::table('categories')->insert(['nombre' => 'Reposteria', 'padre' => '66']);
        DB::table('categories')->insert(['nombre' => 'Snacks', 'padre' => '1']);
        DB::table('categories')->insert(['nombre' => 'Bastones de maiz', 'padre' => '72']);
        DB::table('categories')->insert(['nombre' => 'Galletitas copetin', 'padre' => '72']);
        DB::table('categories')->insert(['nombre' => 'Maiz saborizado', 'padre' => '72']);
        DB::table('categories')->insert(['nombre' => 'Mani', 'padre' => '72']);
        DB::table('categories')->insert(['nombre' => 'Leche en polvo', 'padre' => '1']);
        DB::table('categories')->insert(['nombre' => 'Bebidas', 'padre' => '0']);
        DB::table('categories')->insert(['nombre' => 'Bebidas sin alcohol', 'padre' => '78']);
        DB::table('categories')->insert(['nombre' => 'Gaseosas', 'padre' => '79']);
        DB::table('categories')->insert(['nombre' => 'Jugos', 'padre' => '79']);
        DB::table('categories')->insert(['nombre' => 'Amargos', 'padre' => '79']);
        DB::table('categories')->insert(['nombre' => 'Energizantes', 'padre' => '79']);
        DB::table('categories')->insert(['nombre' => 'Bebidas sin alcohol', 'padre' => '78']);
        DB::table('categories')->insert(['nombre' => 'Cerveza', 'padre' => '84']);
        DB::table('categories')->insert(['nombre' => 'Vinos', 'padre' => '84']);
        DB::table('categories')->insert(['nombre' => 'Aperitivos', 'padre' => '84']);
        DB::table('categories')->insert(['nombre' => 'Champagne y espumantes', 'padre' => '84']);
        DB::table('categories')->insert(['nombre' => 'Frescos', 'padre' => '0']);
        DB::table('categories')->insert(['nombre' => 'Lacteos', 'padre' => '89']);
        DB::table('categories')->insert(['nombre' => 'Leches', 'padre' => '90']);
        DB::table('categories')->insert(['nombre' => 'Yogures', 'padre' => '90']);
        DB::table('categories')->insert(['nombre' => 'Dulce de leche', 'padre' => '90']);
        DB::table('categories')->insert(['nombre' => 'Mantecas y margarinas', 'padre' => '90']);
        DB::table('categories')->insert(['nombre' => 'Fiambres', 'padre' => '89']);
        DB::table('categories')->insert(['nombre' => 'Salchichas y pates', 'padre' => '95']);
        DB::table('categories')->insert(['nombre' => 'Encurtidos a granel', 'padre' => '95']);
        DB::table('categories')->insert(['nombre' => 'Fiambres', 'padre' => '95']);
        DB::table('categories')->insert(['nombre' => 'Frutas y verduras', 'padre' => '89']);
        DB::table('categories')->insert(['nombre' => 'Frutas', 'padre' => '99']);
        DB::table('categories')->insert(['nombre' => 'Verduras', 'padre' => '99']);
        DB::table('categories')->insert(['nombre' => 'Frutas secas y disecadas', 'padre' => '99']);
        DB::table('categories')->insert(['nombre' => 'Champignones', 'padre' => '99']);
        DB::table('categories')->insert(['nombre' => 'Quesos', 'padre' => '89']);
        DB::table('categories')->insert(['nombre' => 'Quesos especiales', 'padre' => '104']);
        DB::table('categories')->insert(['nombre' => 'Queso rallado', 'padre' => '104']);
        DB::table('categories')->insert(['nombre' => 'Queso muzzarella', 'padre' => '104']);
        DB::table('categories')->insert(['nombre' => 'Queso crema y untables', 'padre' => '104']);
        DB::table('categories')->insert(['nombre' => 'Pescados y mariscos', 'padre' => '89']);
        DB::table('categories')->insert(['nombre' => 'Pescado entero', 'padre' => '109']);
        DB::table('categories')->insert(['nombre' => 'Camarones y langostinos', 'padre' => '109']);
        DB::table('categories')->insert(['nombre' => 'Pulpos y sepias', 'padre' => '109']);
        DB::table('categories')->insert(['nombre' => 'Calamares', 'padre' => '109']);
        DB::table('categories')->insert(['nombre' => 'Carniceria', 'padre' => '89']);
        DB::table('categories')->insert(['nombre' => 'Carnes', 'padre' => '114']);
        DB::table('categories')->insert(['nombre' => 'Aves', 'padre' => '114']);
        DB::table('categories')->insert(['nombre' => 'Embutidos', 'padre' => '114']);
        DB::table('categories')->insert(['nombre' => 'Carnes elaboradas', 'padre' => '114']);
        DB::table('categories')->insert(['nombre' => 'Huevos', 'padre' => '89']);
        DB::table('categories')->insert(['nombre' => 'Huevos color', 'padre' => '119']);
        DB::table('categories')->insert(['nombre' => 'Huevos blanco', 'padre' => '119']);
        DB::table('categories')->insert(['nombre' => 'Huevo codorniz', 'padre' => '119']);
        DB::table('categories')->insert(['nombre' => 'Huevos deshidratados', 'padre' => '119']);
        DB::table('categories')->insert(['nombre' => 'Pastas frescas y tapas', 'padre' => '89']);
        DB::table('categories')->insert(['nombre' => 'Fideos y ñoquis', 'padre' => '124']);
        DB::table('categories')->insert(['nombre' => 'Pastas rellenas', 'padre' => '124']);
        DB::table('categories')->insert(['nombre' => 'Tapas para pacualina y empanadas', 'padre' => '124']);
        DB::table('categories')->insert(['nombre' => 'Masas preparadas', 'padre' => '124']);
        DB::table('categories')->insert(['nombre' => 'Congelados', 'padre' => '0']);
        DB::table('categories')->insert(['nombre' => 'Helados y postres', 'padre' => '129']);
        DB::table('categories')->insert(['nombre' => 'Postres helados', 'padre' => '130']);
        DB::table('categories')->insert(['nombre' => 'Yogur helados', 'padre' => '130']);
        DB::table('categories')->insert(['nombre' => 'Helados en pote', 'padre' => '130']);
        DB::table('categories')->insert(['nombre' => 'Helados en palito', 'padre' => '130']);
        DB::table('categories')->insert(['nombre' => 'Frutas congeladas', 'padre' => '129']);
        DB::table('categories')->insert(['nombre' => 'Frutillas', 'padre' => '135']);
        DB::table('categories')->insert(['nombre' => 'Arandanos', 'padre' => '135']);
        DB::table('categories')->insert(['nombre' => 'Frambuesas', 'padre' => '135']);
        DB::table('categories')->insert(['nombre' => 'Mango', 'padre' => '135']);
        DB::table('categories')->insert(['nombre' => 'Comidas congeladas', 'padre' => '129']);
        DB::table('categories')->insert(['nombre' => 'Pizzas y Pizzetas', 'padre' => '140']);
        DB::table('categories')->insert(['nombre' => 'Pastas congeladas', 'padre' => '140']);
        DB::table('categories')->insert(['nombre' => 'Panificados', 'padre' => '140']);
        DB::table('categories')->insert(['nombre' => 'Croquetas', 'padre' => '140']);
        DB::table('categories')->insert(['nombre' => 'Congelados de pollo', 'padre' => '129']);
        DB::table('categories')->insert(['nombre' => 'Pollos', 'padre' => '145']);
        DB::table('categories')->insert(['nombre' => 'Rebozados de pollo', 'padre' => '145']);
        DB::table('categories')->insert(['nombre' => 'Hamburguesas y milanesas', 'padre' => '145']);
        DB::table('categories')->insert(['nombre' => 'Hamburguesas', 'padre' => '145']);
        DB::table('categories')->insert(['nombre' => 'Milanesas', 'padre' => '145']);
        DB::table('categories')->insert(['nombre' => 'Pescados y mariscos', 'padre' => '129']);
        DB::table('categories')->insert(['nombre' => 'Rebozados de pescado', 'padre' => '151']);
        DB::table('categories')->insert(['nombre' => 'Filetes congelados', 'padre' => '151']);
        DB::table('categories')->insert(['nombre' => 'Souffle', 'padre' => '151']);
        DB::table('categories')->insert(['nombre' => 'Paella de mariscos', 'padre' => '151']);
        DB::table('categories')->insert(['nombre' => 'Vegetales congelados', 'padre' => '129']);
        DB::table('categories')->insert(['nombre' => 'Espinacas', 'padre' => '156']);
        DB::table('categories')->insert(['nombre' => 'Acelga', 'padre' => '156']);
        DB::table('categories')->insert(['nombre' => 'Arvejas', 'padre' => '156']);
        DB::table('categories')->insert(['nombre' => 'Cebollas', 'padre' => '156']);
        DB::table('categories')->insert(['nombre' => 'Papas congeladas/Fritas', 'padre' => '129']);
        DB::table('categories')->insert(['nombre' => 'Papas baston', 'padre' => '161']);
        DB::table('categories')->insert(['nombre' => 'Papas noisettes', 'padre' => '161']);
        DB::table('categories')->insert(['nombre' => 'Papas con formas', 'padre' => '161']);
        DB::table('categories')->insert(['nombre' => 'Papas estilo casero', 'padre' => '161']);
    }
}
