<?php

return [
    'videos' => [
        'web' => [
            'title' => 'Demo web',
            'file' => 'videos/demo-web-guiada-20260923.mp4',
            'poster' => 'images/landing/demo-web-guiada-20260923.jpg',
            'duration' => '2:09',
            'description' => 'Del registro a la compra y el consumo de alimentos: un recorrido narrado con capturas reales y datos de ejemplo.',
            'steps' => [
                'Crear una cuenta y completar la puesta en marcha: perfil, objetivo y grupo familiar.',
                'Elegir organizar las comidas y crear el Hogar López.',
                'Cargar 200 g de arroz largo fino en Mi cocina.',
                'Crear una receta de arroz casero con ingredientes y preparación para dos porciones.',
                'Definir un presupuesto mensual de ARS 10.000.',
                'Agregar la receta al plan de almuerzo y elegir cuatro porciones.',
                'Revisar los faltantes: el arroz manual no está vinculado al ingrediente de la receta, por lo que se solicitan 400 g.',
                'Generar la lista de compras, registrar ARS 3 por gramo y elegir incorporar la compra al stock.',
                'Confirmar la compra por ARS 1.200 y comprobar que la lista queda completada.',
                'Consultar el presupuesto: ARS 1.200 gastados y ARS 8.800 disponibles.',
                'Revisar los 400 g incorporados a Mi cocina y su vínculo con el ingrediente.',
                'Registrar cuatro porciones cocinadas con descuento de ingredientes.',
                'Comprobar el consumo de 400 g y consultar el historial de movimientos. Los 200 g manuales quedan separados.',
            ],
            'note' => 'En este ejemplo, el producto cargado manualmente no está vinculado al ingrediente de la receta. La compra y el consumo se realizan sobre el producto vinculado.',
        ],
        'android' => [
            'title' => 'Demo Android',
            'file' => 'videos/demo-android-guiada-20260923.mp4',
            'poster' => 'images/landing/demo-android-guiada-20260923.jpg',
            'subtitles' => 'videos/demo-android-guiada-20260923.vtt',
            'duration' => '1:32',
            'description' => 'Acompañá a Martín desde su cocina hasta la compra: una demo narrada de la app en un Samsung, con datos de ejemplo.',
            'steps' => [
                'Ingresar al mismo hogar usado en la web y revisar los accesos de Inicio.',
                'Consultar Mi cocina: alimentos, cantidades y vencimientos.',
                'Abrir un producto y revisar su detalle.',
                'Consultar la receta de arroz casero y sus ingredientes.',
                'Abrir el plan preparado y revisar las cuatro porciones.',
                'Consultar la lista de compras y los productos faltantes.',
                'Registrar 400 g de arroz por ARS 1.200 y revisar los datos antes de finalizar.',
                'Confirmar la compra y verificar su registro.',
                'Volver a Mi cocina: el stock muestra 600 g de arroz disponibles.',
                'Consultar el presupuesto: ARS 2.400 gastados y ARS 7.600 disponibles.',
                'Actualizar la vista para consultar la información compartida entre web y app.',
            ],
            'note' => 'Grabado en un Samsung S23 Ultra con la app 1.0.8. El recorrido está editado por etapas y utiliza una cuenta y un hogar de ejemplo.',
        ],
    ],
];
